## no critic qw(RequirePodSections)    # -*- cperl -*-
# This file is auto-generated by the Perl TeX::Hyphen::Pattern Suite hyphen
# pattern catalog generator. This code generator comes with the
# TeX::Hyphen::Pattern module distribution in the tools/ directory
#
# Do not edit this file directly.

## no critic qw(ProhibitLongLines)
# $Id: build_catalog.pl 119 2009-08-17 05:49:22Z roland $
# $Revision: 119 $
# $HeadURL: svn+ssh://ipenburg.xs4all.nl/srv/svnroot/rhonda/trunk/TeX-Hyphen-Pattern/tools/build_catalog.pl $
# $Date: 2009-08-17 07:49:22 +0200 (Mon, 17 Aug 2009) $
## use critic

package TeX::Hyphen::Pattern::Mr;
use strict;
use warnings;
use 5.006000;
use utf8;

our $VERSION = '0.05';

my $pattern_file = q{};
while (<DATA>) {
	 $pattern_file .= $_;
}

use Class::Meta::Express qw(class ctor has meta method);

class {

    ctor 'new';

    method data => sub {
		$pattern_file;
	};

    method version => sub {
		$VERSION;
	};

};

1;
## no critic qw(RequirePodAtEnd RequireASCII)
=encoding utf8

=head1 C<Mr> hyphenation pattern class

=head1 Copyright

=begin text
Marathi Hyphenation Patterns

(more info about the licence to be added later)

% These patterns originate from
%    http://git.savannah.gnu.org/cgit/smc.git/tree/hyphenation)
% and have been adapted for hyph-utf8 (for use in TeX).
%
%  Hyphenation for Marathi
%  Copyright (C) 2008-2010 Santhosh Thottingal <santhosh.thottingal@gmail.com>
%
%  This library is free software; you can redistribute it and/or
%  modify it under the terms of the GNU Lesser General Public
%  License as published by the Free Software Foundation;
%  version 3 or later version of the License.
%
%  This library is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%  Lesser General Public License for more details.
%
%  You should have received a copy of the GNU Lesser General Public
%  License along with this library; if not, write to the Free Software
%  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
%

=end text

=cut

__DATA__
\patterns{
2‍2
1‌1
अ1
आ1
इ1
ई1
उ1
ऊ1
ऋ1
ॠ1
ऌ1
ॡ1
ए1
ऐ1
ओ1
औ1
ा1
ि1
ी1
ु1
ू1
ृ1
ॄ1
ॢ1
ॣ1
े1
ै1
ो1
ौ1
1क
1ख
1ग
1घ
1ङ
1च
1छ
1ज
1झ
1ञ
1ट
1ठ
1ड
1ढ
1ण
1त
1थ
1द
1ध
1न
1प
1फ
1ब
1भ
1म
1य
1र
1ल
1ळ
1व
1श
1ष
1स
1ह
2ँ1
2ं1
2ः1
2ऽ1
2॑1
2॒1
2्2

}
\hyphenation{

}
