## no critic qw(RequirePodSections)    # -*- cperl -*-
# This file is auto-generated by the Perl TeX::Hyphen::Pattern Suite hyphen
# pattern catalog generator. This code generator comes with the
# TeX::Hyphen::Pattern module distribution in the tools/ directory
#
# Do not edit this file directly.

## no critic qw(ProhibitLongLines)
# $Id: build_catalog.pl 119 2009-08-17 05:49:22Z roland $
# $Revision: 119 $
# $HeadURL: svn+ssh://ipenburg.xs4all.nl/srv/svnroot/rhonda/trunk/TeX-Hyphen-Pattern/tools/build_catalog.pl $
# $Date: 2009-08-17 07:49:22 +0200 (Mon, 17 Aug 2009) $
## use critic

package TeX::Hyphen::Pattern::Pa;
use strict;
use warnings;
use 5.006000;
use utf8;

our $VERSION = '0.05';

my $pattern_file = q{};
while (<DATA>) {
	 $pattern_file .= $_;
}

use Class::Meta::Express qw(class ctor has meta method);

class {

    ctor 'new';

    method data => sub {
		$pattern_file;
	};

    method version => sub {
		$VERSION;
	};

};

1;
## no critic qw(RequirePodAtEnd RequireASCII)
=encoding utf8

=head1 C<Pa> hyphenation pattern class

=head1 Copyright

=begin text
Panjabi Hyphenation Patterns

(more info about the licence to be added later)

% These patterns originate from
%    http://git.savannah.gnu.org/cgit/smc.git/tree/hyphenation)
% and have been adapted for hyph-utf8 (for use in TeX).
%
%  Hyphenation for Panjabi
%  Copyright (C) 2008-2010 Santhosh Thottingal <santhosh.thottingal@gmail.com>
%
%  This library is free software; you can redistribute it and/or
%  modify it under the terms of the GNU Lesser General Public
%  License as published by the Free Software Foundation;
%  version 3 or later version of the License.
%
%  This library is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%  Lesser General Public License for more details.
%
%  You should have received a copy of the GNU Lesser General Public
%  License along with this library; if not, write to the Free Software
%  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
%

=end text

=cut

__DATA__
\patterns{
2‍2
1‌1
ਅ1
ਆ1
ਇ1
ਈ1
ਉ1
ਊ1
ਏ1
ਐ1
ਓ1
ਔ1
ਾ1
ਿ1
ੀ1
ੁ1
ੂ1
ੇ1
ੈ1
ੋ1
ੌ1
1ਕ
1ਖ
1ਗ
1ਘ
1ਙ
1ਚ
1ਛ
1ਜ
1ਝ
1ਞ
1ਟ
1ਠ
1ਡ
1ਢ
1ਣ
1ਤ
1ਥ
1ਦ
1ਧ
1ਨ
1ਪ
1ਫ
1ਬ
1ਭ
1ਮ
1ਯ
1ਰ
1ਲ
1ਲ਼
1ਵ
1ਸ਼
1ਸ
1ਹ
2ਁ1
2ਂ1
2ਃ1
2੍2
2ੰ2
2ੱ2

}
\hyphenation{

}
